packages:
  - .
  - test/typescript-v7

allowBuilds:
  core-js: false
  simple-git-hooks: false
minimumReleaseAgeExclude:
  - '@typescript/*'
  - typescript
  - ts-checker-rspack-plugin
  - '@rstest/*'
